function notaAleatoria() {
  return Math.floor(Math.random() * 5) + 1;
}

module.exports = {
  up: (queryInterface) =>
    queryInterface.bulkInsert(
      'notas',
      [
        {
          nota: notaAleatoria(),
          restaurante_id: 11,
          cliente_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 11,
          cliente_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 11,
          cliente_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 11,
          cliente_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 11,
          cliente_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 11,
          cliente_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 11,
          cliente_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 11,
          cliente_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 11,
          cliente_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 11,
          cliente_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 12,
          cliente_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 12,
          cliente_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 12,
          cliente_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 12,
          cliente_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 12,
          cliente_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 12,
          cliente_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 12,
          cliente_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 12,
          cliente_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 12,
          cliente_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 12,
          cliente_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 13,
          cliente_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 13,
          cliente_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 13,
          cliente_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 13,
          cliente_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 13,
          cliente_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 13,
          cliente_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 13,
          cliente_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 13,
          cliente_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 13,
          cliente_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 13,
          cliente_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 14,
          cliente_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 14,
          cliente_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 14,
          cliente_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 14,
          cliente_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 14,
          cliente_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 14,
          cliente_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 14,
          cliente_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 14,
          cliente_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 14,
          cliente_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 14,
          cliente_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 15,
          cliente_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 15,
          cliente_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 15,
          cliente_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 15,
          cliente_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 15,
          cliente_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 15,
          cliente_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 15,
          cliente_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 15,
          cliente_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 15,
          cliente_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 15,
          cliente_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 16,
          cliente_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 16,
          cliente_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 16,
          cliente_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 16,
          cliente_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 16,
          cliente_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 16,
          cliente_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 16,
          cliente_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 16,
          cliente_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 16,
          cliente_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 16,
          cliente_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 17,
          cliente_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 17,
          cliente_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 17,
          cliente_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 17,
          cliente_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 17,
          cliente_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 17,
          cliente_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 17,
          cliente_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 17,
          cliente_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 17,
          cliente_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 17,
          cliente_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 18,
          cliente_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 18,
          cliente_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 18,
          cliente_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 18,
          cliente_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 18,
          cliente_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 18,
          cliente_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 18,
          cliente_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 18,
          cliente_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 18,
          cliente_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 18,
          cliente_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 19,
          cliente_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 19,
          cliente_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 19,
          cliente_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 19,
          cliente_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 19,
          cliente_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 19,
          cliente_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 19,
          cliente_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 19,
          cliente_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 19,
          cliente_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 19,
          cliente_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 20,
          cliente_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 20,
          cliente_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 20,
          cliente_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 20,
          cliente_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 20,
          cliente_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 20,
          cliente_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 20,
          cliente_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 20,
          cliente_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 20,
          cliente_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 20,
          cliente_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 21,
          cliente_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 21,
          cliente_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 21,
          cliente_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 21,
          cliente_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 21,
          cliente_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 21,
          cliente_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 21,
          cliente_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 21,
          cliente_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 21,
          cliente_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 21,
          cliente_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 22,
          cliente_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 22,
          cliente_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 22,
          cliente_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 22,
          cliente_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 22,
          cliente_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 22,
          cliente_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 22,
          cliente_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 22,
          cliente_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 22,
          cliente_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: 22,
          cliente_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    ),
  down: () => {},
};
