function notaAleatoria() {
  return Math.floor(Math.random() * 5) + 1;
}

function restauranteAleatorio() {
  return Math.floor(Math.random() * (22 - 11) + 11);
}

function clienteAleatorio() {
  return Math.floor(Math.random() * 10) + 1;
}

module.exports = {
  up: (queryInterface) =>
    queryInterface.bulkInsert(
      'notas',
      [
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nota: notaAleatoria(),
          restaurante_id: restauranteAleatorio(),
          cliente_id: clienteAleatorio(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    ),
  down: () => {},
};
