function randomRate() {
  return Math.floor(Math.random() * 5) + 1;
}

module.exports = {
  up: (queryInterface) =>
    queryInterface.bulkInsert(
      'rates',
      [
        {
          rate: randomRate(),
          restaurant_id: 11,
          client_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 11,
          client_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 11,
          client_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 11,
          client_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 11,
          client_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 11,
          client_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 11,
          client_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 11,
          client_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 11,
          client_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 11,
          client_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 12,
          client_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 12,
          client_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 12,
          client_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 12,
          client_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 12,
          client_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 12,
          client_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 12,
          client_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 12,
          client_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 12,
          client_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 12,
          client_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 13,
          client_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 13,
          client_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 13,
          client_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 13,
          client_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 13,
          client_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 13,
          client_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 13,
          client_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 13,
          client_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 13,
          client_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 13,
          client_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 14,
          client_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 14,
          client_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 14,
          client_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 14,
          client_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 14,
          client_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 14,
          client_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 14,
          client_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 14,
          client_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 14,
          client_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 14,
          client_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 15,
          client_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 15,
          client_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 15,
          client_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 15,
          client_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 15,
          client_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 15,
          client_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 15,
          client_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 15,
          client_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 15,
          client_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 15,
          client_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 16,
          client_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 16,
          client_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 16,
          client_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 16,
          client_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 16,
          client_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 16,
          client_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 16,
          client_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 16,
          client_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 16,
          client_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 16,
          client_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 17,
          client_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 17,
          client_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 17,
          client_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 17,
          client_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 17,
          client_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 17,
          client_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 17,
          client_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 17,
          client_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 17,
          client_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 17,
          client_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 18,
          client_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 18,
          client_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 18,
          client_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 18,
          client_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 18,
          client_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 18,
          client_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 18,
          client_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 18,
          client_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 18,
          client_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 18,
          client_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 19,
          client_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 19,
          client_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 19,
          client_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 19,
          client_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 19,
          client_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 19,
          client_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 19,
          client_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 19,
          client_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 19,
          client_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 19,
          client_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 20,
          client_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 20,
          client_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 20,
          client_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 20,
          client_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 20,
          client_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 20,
          client_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 20,
          client_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 20,
          client_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 20,
          client_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 20,
          client_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 21,
          client_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 21,
          client_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 21,
          client_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 21,
          client_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 21,
          client_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 21,
          client_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 21,
          client_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 21,
          client_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 21,
          client_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 21,
          client_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 22,
          client_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 22,
          client_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 22,
          client_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 22,
          client_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 22,
          client_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 22,
          client_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 22,
          client_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 22,
          client_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 22,
          client_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          rate: randomRate(),
          restaurant_id: 22,
          client_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    ),
  down: () => {},
};
